# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("importe_piezo_hubeau works", {
  expect_true(inherits(importe_piezo_hubeau, "function")) 
  
  tmp<-importe_piezo_hubeau(code_bss="04193X0022/S2-6",
                     date_debut = as.Date("2010-01-01"),
                     date_fin=as.Date("2011-01-01"))
 
  expect_true(nrow(tmp)==366) 
})
