# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("importe_debit_dates_dispo works", {
  
  test<-importe_debit_dates_dispo()
  expect_true(class(test)=="data.frame")
  expect_true(nrow(test)>0)
  
})
