# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("importe_stations_piezo_hubeau works", {
  expect_true(inherits(importe_stations_piezo_hubeau, "function")) 
  
    data_old_bss<-importe_stations_piezo_hubeau(code_bss=c("04193X0022/S2-6",
                                                       "03862X0057/PZ"))
    

  expect_true(nrow(data_old_bss)==2) 
data_new_bss<-importe_stations_piezo_hubeau(nouveau_bss=c("BSS001BHVJ",
                                                       "BSS001DJDP",
                                                          "BSS001ESVY"))
  expect_true(nrow(data_new_bss)==3) 
  
  
   piezo_vilaine<-importe_stations_piezo_hubeau(shp_emprise=sage_vilaine)
  expect_true(nrow(data_new_bss)>62) 
  
})
