# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

test_that("calcule_flux_annuels works", {
  datafile <- system.file("nitrates.csv", package = "calculeflux")
nitrates <- read.csv2(datafile, encoding = "UTF-8")
nitrates$DatePrel<-nitrates$DatePrel%>%as.Date()


datafile <- system.file("debit.csv", package = "calculeflux")
debit <- read.csv2(datafile, encoding = "UTF-8")
debit$date_obs_elab<-debit$date_obs_elab%>%as.Date()

flux_vilaine<-calcule_flux_annuels(annees=c(2016,2021),
                     mois_debut=10,
                     analyses0=nitrates,
                     debit0=debit
                     )
  
  expect_true(nrow(flux_vilaine)>0) 
})
