# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("importe_qualite_hubeau works with more 20000 lines", {
 donnees<-importe_qualite_hubeau(code_station=c("03174000"),
                                           date_debut = as.Date("2010-01-01"),
                                       date_fin = as.Date("2010-11-27"))
  expect_true(class(donnees)=="data.frame")
  expect_true(nrow(donnees)>29000)
})

test_that("importe_qualite_hubeau works with more 20000 lines", {
 donnees<-importe_qualite_hubeau(code_station=c("03174000"),
                                           date_debut = as.Date("2010-01-01"),
                                       date_fin = as.Date("2010-01-31"))
  expect_true(class(donnees)=="data.frame")
  expect_true(nrow(donnees)>2000)
})

