# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("importe_stations_hydrometriques_hubeau works", {
  utils::data("sage_vilaine", package="calculeflux")
  test<-importe_stations_hydrometriques_hubeau(emprise=sage_vilaine)
  expect_true(nrow(test)>100) 
})
