# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

test_that("importe_BV_amont works", {
  shp<-importe_BV_amont(X=381425.6,
                      Y=6755598)
  
  expect_true("sf"%in%class(shp)) 
  expect_true(is.numeric(shp$surface_ha))
  
})
