# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("calcule_hydraulicite works", {
  expect_true(inherits(calcule_hydraulicite, "function")) 
})


datafile <- system.file("debit.csv", package = "calculeflux")
debit <- read.csv2(datafile, encoding = "UTF-8")
debit$date_obs_elab<-debit$date_obs_elab%>%as.Date()

# test 1
date_debut_calcul<-"2022-09-15"%>%as.Date()
date_fin_calcul<-"2022-09-30"%>%as.Date()

test<-calcule_hydraulicite(debit,
                     col_dates_debit="date_obs_elab",
                     col_debits="resultat_obs_elab",
                     date_debut_calcul,
                     date_fin_calcul)

test_that("calcule hydraulicite 1 OK", {
  expect_equal(test, 0.7300643)
})


# test 2
date_debut_calcul<-"2019-12-31"%>%as.Date()
date_fin_calcul<-"2020-01-01"%>%as.Date()

test<-calcule_hydraulicite(debit,
                     col_dates_debit="date_obs_elab",
                     col_debits="resultat_obs_elab",
                     date_debut_calcul,
                     date_fin_calcul)

test_that("calcule hydraulicite 2 OK", {
  expect_equal(test, 1.281062)
})


