# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("importe_debit_hubeau works", {
  
  test<-importe_debit_hubeau(code_entite="J9300611",
                     date_debut_obs_elab=as.Date("2010-01-01"),
                     date_fin_obs_elab=as.Date("2011-12-31"))
  
  expect_true(class(test)=="data.frame")
  expect_true(nrow(test)==729) 
  expect_true(all(names(test)%in%c("code_station", "date_obs_elab", "resultat_obs_elab")))
})
