# WARNING - Generated by {fusen} from dev/flat_calcule_flux_wrtds.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("calcule_flux_wrtds works", {
  expect_true(inherits(calcule_flux_wrtds, "function"))
})
