# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


 date_debut_calcul<-"2007-01-01"%>%as.Date()
 date_fin_calcul<-"2007-12-31"%>%as.Date()
  
datafile <- system.file("nitrates.csv", package = "calculeflux")
nitrates <- read.csv2(datafile, encoding = "UTF-8")
nitrates$DatePrel<-nitrates$DatePrel%>%as.Date()

 datafile <- system.file("debit.csv", package = "calculeflux")
debit <- read.csv2(datafile, encoding = "UTF-8")
debit$date_obs_elab<-debit$date_obs_elab%>%as.Date()

# test M1
test<-calcule_flux(
  nitrates,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  debit,
  methode = "M1",
  date_debut_calcul=date_debut_calcul,
  date_fin_calcul=date_fin_calcul
)
test_that("calcule de flux M1 OK", {
  expect_equal(test, 99689274)
})

# test M2
test<-calcule_flux(
  nitrates,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  debit,
  methode = "M2",
  date_debut_calcul=date_debut_calcul,
  date_fin_calcul=date_fin_calcul
)
test_that("calcule de flux M2 OK", {
  expect_equal(test, 112724458)
})

# test M3
test<-calcule_flux(
  nitrates,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  debit,
  methode = "M3",
  date_debut_calcul=date_debut_calcul,
  date_fin_calcul=date_fin_calcul
)
test_that("calcule de flux M3 OK", {
  expect_equal(test, 128970173)
})

# test M4
test<-calcule_flux(
  nitrates,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  debit,
  methode = "M4",
  date_debut_calcul=date_debut_calcul,
  date_fin_calcul=date_fin_calcul
)
test_that("calcule de flux M4 OK", {
  expect_equal(test, 77044947)
})

# test M5
test<-calcule_flux(
  nitrates,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  debit,
  methode = "M5",
  date_debut_calcul=date_debut_calcul,
  date_fin_calcul=date_fin_calcul
)
test_that("calcule de flux M5 OK", {
  expect_equal(test, 87119201)
})

# test M6
test<-calcule_flux(
  nitrates,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  debit,
  methode = "M6",
  date_debut_calcul=date_debut_calcul,
  date_fin_calcul=date_fin_calcul
)

test_that("calcule de flux M6 OK", {
  expect_equal(round(test), 86453022)
})

# test M9
test<-calcule_flux(
  nitrates,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  debit,
  methode = "M9",
  date_debut_calcul=date_debut_calcul,
  date_fin_calcul=date_fin_calcul
)

test_that("calcule de flux M9 OK", {
  expect_equal(test, 85412992)
})


