# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

test_that("importe_qualite_hubeau works", {
  donnees<-importe_qualite_hubeau(code_station="04211950", 
                                code_parametre = "1340",
                                code_support="3")
  expect_true(class(donnees)=="data.frame")
  expect_true(nrow(donnees)>138)
})
