# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand



test_that("importe_debit works", {
  expect_true(inherits(importe_debit, "function")) 
})
test<-importe_debit(X=381425.6, 
                    Y=6755598, 
                    date_debut=as.Date("2010-01-09"), 
                    date_fin = as.Date("2010-01-17"))

test_that("import de debit fonctionne", {
  expect_equal(nrow(test), 9)
})


