# WARNING - Generated by {fusen} from dev/flat_calcule_flux_wrtds.Rmd: do not edit by hand # nolint: line_length_linter.

#' calcule_flux_wrtds Title
#'
#' @return 1
#' @export
#'
#' @examples
#' calcule_flux_wrtds()
calcule_flux_wrtds <- function() {
  1
}
