# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Calculus of hydraulicity
#' 
#' Calculus hydraulicity (Ha) for A period (by default : a = an hydrological year)
#' 
#' Ha = Qa / Qmean 
#' Qa = total flow during period A
#' Qmean = medium flow on period A over years
#' 
#' Ha < 1 mean tha the period is dry whereas Ha > 1 mean that period is wet.
#' 
#' @param debit dataframe with daily mean flow rate in m3/s
#' @param col_dates_debit Name of the column with the date of flow rate. Default : date_obs_elab
#' @param col_debits Name of the column with the flowrate values. Default : resultat_obs_elab
#' @param date_debut_calcul Date of begining of calculus (for instance "2010-10-01" to start calculus from 1st of october 2010)
#' @param date_fin_calcul Date of ending of calculus (for instance "2011-09-30" to end calculus to 30 of september 2011)
#' 
#' 
#' @return value of hydraulicity for the period (numeric)
#' 
#' @export
#' @examples
#'
#' date_debut_calcul<-"2022-09-15"%>%as.Date()
#' date_fin_calcul<-"2022-09-30"%>%as.Date()
#'
#' datafile <- system.file("debit.csv", package = "calculeflux")
#' debit <- read.csv2(datafile, encoding = "UTF-8")
#' debit$date_obs_elab<-debit$date_obs_elab%>%as.Date()
#'
#'
#' calcule_hydraulicite(debit,
#'                      col_dates_debit="date_obs_elab",
#'                      col_debits="resultat_obs_elab",
#'                      date_debut_calcul,
#'                      date_fin_calcul)
#'
#' # example 2
#'
#' datafile <- system.file("debit.csv", package = "calculeflux")
#' debit <- read.csv2(datafile, encoding = "UTF-8")
#' debit$date_obs_elab<-debit$date_obs_elab%>%as.Date()
#'
#' date_debut_calcul=paste0(seq(2002,2021),"-10-01")%>%as.Date
#' date_fin_calcul=paste0(seq(2003,2022),"-09-30")%>%as.Date
#'
#' annees_hydro<-data.frame(date_debut_calcul=date_debut_calcul, 
#'                          date_fin_calcul=date_fin_calcul,
#'                          nom=paste0(seq(2002,2021),
#'                                     "-",
#'                                     seq(2003,2022)))
#'
#'
#'
#' tmp<-lapply(seq(2002:2021),
#' function(x){calcule_hydraulicite(debit,
#'                      date_debut_calcul=annees_hydro$date_debut_calcul[x],
#'                      date_fin_calcul=annees_hydro$date_fin_calcul[x])
#'   }
#' )
#'
#'
#' tmp<-unlist(tmp)
#' tmp<-data.frame(annee=annees_hydro$nom, hydraulicite=tmp)
#'
#'
#' library(ggplot2)
#'
#' ggplot2::ggplot(tmp, ggplot2::aes(annee, hydraulicite)) +
#'   ggplot2::geom_bar(stat="identity") +
#'   ggplot2::ylab("hydraulicite") + 
#'   ggplot2::geom_hline(yintercept=1)+
#'   ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust=0.5)) +
#'   ggplot2::ggtitle("Hydraulicit\u00e9 sur la Vilaine \u00e0 Rieux",
#'           subtitle="station hydrom\u00e9trique J930061101")
#'
#'
#'
calcule_hydraulicite <- function(debit,
                                 col_dates_debit="date_obs_elab",
                                 col_debits="resultat_obs_elab",
                                 date_debut_calcul,
                                 date_fin_calcul){
    
  
    if (!is.data.frame(debit)) {
    stop("debit should be dataframe")
  }
  if (!is.character(col_dates_debit)) {
    stop("col_dates_debit should be character")
  }
  if (!is.character(col_debits)) {
    stop("col_debits should be character")
  }
    if (!(col_dates_debit %in% names(debit))) {
    stop("col_dates_debit must be one of the column name from data.frame debit")
  }
  if (!(col_debits %in% names(debit))) {
    stop("col_debits must be one of the column name from data.frame debit")
  }
  if (!class(debit[[col_dates_debit]]) %in% c("Date", "POSIXct", "POSIXt", "POSIXlt")) {
    stop("Class of flow rates dates should be date, POSIXct or POSIXlt")
  }
  if (!class(debit[[col_debits]]) %in% c("numeric")) {
    stop("Class of analysis results should be numeric")
  }
  if (!class(date_debut_calcul) %in% c("Date", "POSIXct", "POSIXt", "POSIXlt")) {
    stop("Class of date_debut_calcul should be date, POSIXct or POSIXlt")
  }
  if (!class(date_fin_calcul) %in% c("Date", "POSIXct", "POSIXt", "POSIXlt")) {
    stop("Class of date_fin_calcul should be date, POSIXct or POSIXlt")
  }

   
  # on retient la moyenne des résultats de debits si plusieurs résultats sont disponibles à la même date
  debit<-debit%>%dplyr::group_by(get(col_dates_debit))%>%dplyr::summarise(QJM=mean(.data[[col_debits]], na.rm=T))
  names(debit)<-c("DatePrel", "QJM")
  
  # date_debut_calcul<-'2007-12-01'
  # date_fin_calcul<-'2008-01-31'

  date_debut_calcul<-date_debut_calcul%>%as.Date()
  date_fin_calcul<-date_fin_calcul%>%as.Date()
  
   if (date_debut_calcul>=date_fin_calcul) {
    stop("date_debut_calcul must be strictly lower than date_fin_calcul")
   }
  
  debit$jour_mois<-paste0("2000",format(debit[["DatePrel"]],"-%m-%d"))%>%as.Date()
  
  # si le jour de debut est avant le jour de fin dans une annee civile alors on retient toutes les données entre date de debut et date de fin (ex de janvier à mars)
  if((format(date_debut_calcul,"%m")%>%as.numeric*100)+(format(date_debut_calcul,"%d")%>%as.numeric)<
     (format(date_fin_calcul,"%m")%>%as.numeric*100)+(format(date_fin_calcul,"%d")%>%as.numeric))
  {jour_mois_debut<-paste0("2000",date_debut_calcul%>%format("-%m-%d"))%>%as.Date()
  jour_mois_fin<-paste0("2000",date_fin_calcul%>%format("-%m-%d"))%>%as.Date()
  debit<-debit%>%subset(jour_mois>=jour_mois_debut & jour_mois<=jour_mois_fin)
  }
  # si c'est l'inverse, on retient les données du mois de fin au mois de début (ex : si date de debut = dec 2020 et date de fin = janvier 2021, on retient totues les données de dec à mars)
  if(format(date_debut_calcul,"%m")%>%as.numeric*100+format(date_debut_calcul,"%d")%>%as.numeric>
     format(date_fin_calcul,"%m")%>%as.numeric*100+format(date_fin_calcul,"%d")%>%as.numeric)
  {jour_mois_debut<-paste0("2000",date_debut_calcul%>%format("-%m-%d"))%>%as.Date()
  jour_mois_fin<-paste0("2000",date_fin_calcul%>%format("-%m-%d"))%>%as.Date()
  debit<-debit%>%subset(jour_mois>=jour_mois_debut | jour_mois<=jour_mois_fin)
  }
  
  Qa<-debit%>%subset(DatePrel>=date_debut_calcul & DatePrel<=date_fin_calcul)
  Qa<-mean(Qa[["QJM"]], na.rm=T)
  Qmoyen<-mean(debit[["QJM"]], na.rm=T)
  
  Ha<-Qa/Qmoyen
  
  return(Ha)
}
