# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' calcule_flux_annuels
#' 
#' This function calculate ech annual fluxes of a period.
#' For a same date if their are more than one analysis or flow rate values, then 
#' calculus is done by considering the mean (excluding NA) of all the values for the day.
#' 
#' @param annees : vector with first and last years (in numeric) to treat. If you want results for 
#' years 2010-2011, 2011-2012 and 2012-2013, annees should be equal to c(2010,2012)
#' @param mois_debut : numeric indicating wich month to start the hydraulic year 
#' with. Default is 10 (for october).
#' @param analyses0 : data.frame with nitrates results for the different dates (mg/L)
#' @param col_dates_anal : character indicating the name of the column of analyses
#' in which dates are stored. Default = "DatePrel"
#' @param col_analyses : character indicating the name of the column of analyses
#' in which results are stored. Default = "RsAna"
#' @param debit0 : data.frame with daily flow rates results for the different dates (L/s)
#' @param col_dates_debit : character indicating the name of the column of debit
#' in which dates are stored. Default = "date_obs_elab"
#' @param col_valeurs_debits : character indicating the name of the column of debit
#' in which results are stored. Default = "resultat_obs_elab"
#' @param methode : methode used to calculate fluxes. Default = "M6". 
#' See calcule_flux for more details.
#' @param out : required output. Values can be : "flux" : only flux are returned,
#' "hydrau" : only hydraulicity is returned, and "flux_hydrau_pond" : flux, hydraulicity
#' and ponderaty flux by hydraulicity are returned.
#' @param minimum_rs_ana : minimum number of data of concentration in one hydraulic 
#' year to make the calculus. Default = 6 : Calculus are not done for years with 6 
#' or less data of concentrations
#' 
#' 
#' @return data.frame with columns :
#' - annee_hydro : hydraulical year
#' - N_RsAna : number of data of concentration
#' - N_Qjm : number of daily flow rate
#' - nb_jours : number of days during the hydraulical year
#' - debit_tot : annual flow rate in m3/year
#' - flux : flux in kg/year (if analyses in mg/L)
#' - Cmoy :mean of concentration = flux / debit_tot in mg/L
#' - hydraulicity : hydraulicity
#' - flux_pond : flux ponderate by hydraulicity in kg/year (if analyses in mg/L)
#' 
#'  
#' @export
#' @examples
#'    
#' 
#' datafile <- system.file("nitrates.csv", package = "calculeflux")
#' nitrates <- read.csv2(datafile, encoding = "UTF-8")
#' nitrates$DatePrel<-nitrates$DatePrel%>%as.Date()
#' 
#' 
#' datafile <- system.file("debit.csv", package = "calculeflux")
#' debit <- read.csv2(datafile, encoding = "UTF-8")
#' debit$date_obs_elab<-debit$date_obs_elab%>%as.Date()
#' 
#' annees=c(1971,2014)
#'  mois_debut<-9
#'   
#' 
#' 
#' flux_vilaine<-calcule_flux_annuels(annees=c(2010,2015),
#'                      mois_debut=10,
#'                      analyses0=nitrates,
#'                      debit0=debit
#'                      )
#' 
#' 
#' 
calcule_flux_annuels <- function(annees, 
                                 mois_debut=10, 
                                 analyses0, 
                                 col_dates_anal="DatePrel",
                                 col_analyses="RsAna",
                                 debit0,
                                 col_dates_debit="date_obs_elab",
                                 col_valeurs_debits="resultat_obs_elab",
                                 methode="M6",
                                 out="flux_hydrau_pond",
                                 minimum_rs_ana=6){
  
  #astuces pour éviter note no visible binding for global variable
  RsAna <- date_obs_elab <- resultat_obs_elab<- annee_hydro<- NULL
  
  if (!"numeric" %in% class(annees)) {
    stop("calcule_flux_annuels : annees must be a numeric vector")
  }
  if (!all(annees %in% seq(1800, 2200))) {
    stop("calcule_flux_annuels : one or more values of annees are not valid years")
  }
  if(length(annees)>2){stop("calcule_flux_annuels : annees should contain only year 
                            of beginning and year of end of calculation")}
  if (!"numeric" %in% class(mois_debut)) {
    stop("calcule_flux_annuels : mois_debut must be a numeric")
  }
  if (!all(mois_debut %in% seq(1, 12))) {
    stop("calcule_flux_annuels : mois_debut is not a valid month")
  }
  if (!"data.frame" %in% class(analyses0)) {
    stop("calcule_flux_annuels : analyses must be a data.frame")
  }
  if (!"character" %in% class(col_dates_anal)) {
    stop("calcule_flux_annuels : col_dates_anal must be a character")
  }
  if (!col_dates_anal %in% colnames(analyses0)) {
    stop(
      "calcule_flux_annuels : col_dates_anal must be the name of one column of analyses data.frame"
    )
  }
   if (!"character" %in% class(col_analyses)) {
    stop("calcule_flux_annuels : col_dates_anal must be a character")
  }
  if (!col_analyses %in% colnames(analyses0)) {
    stop(
      "calcule_flux_annuels : col_analyses must be the name of one column of analyses data.frame"
    )
  } 
  if (!"data.frame" %in% class(debit0)) {
    stop("calcule_flux_annuels : debit must be a data.frame")
  }
  if (!"character" %in% class(col_dates_debit)) {
    stop("calcule_flux_annuels : col_dates_debit must be a character")
  }
  if (!col_dates_debit %in% colnames(debit0)) {
    stop(
      "calcule_flux_annuels : col_dates_debit must be the name of one column of debit data.frame"
    )
  }
   if (!"character" %in% class(col_valeurs_debits)) {
    stop("calcule_flux_annuels : col_valeurs_debits must be a character")
  }
  if (!col_valeurs_debits %in% colnames(debit0)) {
    stop(
      "calcule_flux_annuels : col_valeurs_debits must be the name of one column of debit data.frame"
    )
  } 
  if (!"character" %in% class(out)) {
    stop("calcule_flux_annuels : out must be a character")
  }
  if (!out %in% c("flux_hydrau_pond", "hydrau", "flux")) {
    stop(
      "calcule_flux_annuels : invalidate value for parameter out"
    )
  } 
  
  debit <- debit0[, c(col_dates_debit, col_valeurs_debits)]
  names(debit) <- c("date_obs_elab",
                    "resultat_obs_elab")
  if (!"Date" %in% class(debit$date_obs_elab)) {
    stop(
      paste0(
        "calcule_flux_annuels : dates from debit data.frame should be of class Date (column ",
        col_dates_debit,
        ")"
      )
    )
  }
  if (!"numeric" %in% class(minimum_rs_ana)) {
    stop(
      paste0(
        "calcule_flux_annuels : minimum_rs_ana should be numeric"
      )
    )
  }
  if (minimum_rs_ana<0 | (minimum_rs_ana-trunc(minimum_rs_ana))!=0) {
    stop(
      paste0(
        "calcule_flux_annuels : minimum_rs_ana should be a positive integer"
      )
    )
  }
  
  analyses<-analyses0[,c(col_dates_anal,col_analyses)]
  names(analyses)<-c("DatePrel", "RsAna")

 if (!"Date" %in% class(analyses$DatePrel)) {
    stop(
      paste0(
        "calcule_flux_annuels : dates from analyses data.frame should be of class Date (column ",
        col_dates_anal,
        ")"
      )
    )
  }
  if (!"numeric" %in% class(analyses$RsAna)) {
    stop(
      paste0(
        "calcule_flux_annuels : values from analyses data.frame should be of class numeric (column ",
        col_analyses,
        ")"
      )
    )
  }
  if (!"numeric" %in% class(analyses$RsAna)) {
    stop(
      paste0(
        "calcule_flux_annuels : values from analyses data.frame should be of class numeric (column ",
        col_analyses,
        ")"
      )
    )
  }
  
# on retient la moyenne des résultats d'analyse si plusieurs résultats sont disponibles à la même date

analyses<-analyses%>%
  dplyr::group_by(DatePrel)%>%
  dplyr::summarise(RsAna=mean(RsAna, na.rm=T))
  
  # on retient la moyenne des résultats de debits si plusieurs résultats sont disponibles à la même date
debit<-debit%>%
  dplyr::group_by(date_obs_elab)%>%
  dplyr::summarise(resultat_obs_elab=mean(resultat_obs_elab, na.rm=T)) 
  
  
# on découpe les données par année hydrologique
seuils_coupure<-paste(seq(min(annees, na.rm=TRUE), max(annees, na.rm=TRUE)+1, by=1),
                      mois_debut,"01",
                      sep="-")%>%as.Date()


if(mois_debut==1){lbl_coupure<-seq(min(annees, na.rm=TRUE), max(annees, na.rm=TRUE), by=1)}else
{lbl_coupure<-paste(seq(min(annees, na.rm=TRUE), max(annees, na.rm=TRUE), by=1),
                   seq(min(annees, na.rm=TRUE)+1, max(annees, na.rm=TRUE)+1, by=1),
                   sep="-")}

analyses$annee_hydro<-cut(analyses$DatePrel, breaks=seuils_coupure, labels=lbl_coupure)
debit$annee_hydro<-cut(debit$date_obs_elab, breaks=seuils_coupure, labels=lbl_coupure)

# calcul du nombre de données de concentration et de debit par annee
resultat_Q<-debit%>%
  subset(!is.na(annee_hydro))%>%
  dplyr::group_by(annee_hydro)%>%
  dplyr::summarise(N_Qjm=dplyr::n())
  

Qannuel<-debit%>%
  subset(!is.na(annee_hydro))%>%
  dplyr::group_by(annee_hydro)%>%
  dplyr::summarise(debit_an=sum(resultat_obs_elab, na.rm=TRUE))

resultat_C<-analyses%>%
  subset(!is.na(annee_hydro))%>%
  dplyr::group_by(annee_hydro)%>%
  dplyr::summarise(N_RsAna=dplyr::n())

resultat<-dplyr::full_join(resultat_C, resultat_Q, by="annee_hydro")

nb_jours<-data.frame(annee_hydro=lbl_coupure,
  nb_jours=difftime(seuils_coupure[2:length(seuils_coupure)],
                   seuils_coupure[1:length(seuils_coupure)-1],
                   units="days")%>%as.numeric)

resultat<-dplyr::full_join(resultat, nb_jours, by="annee_hydro")
resultat<-dplyr::full_join(resultat, Qannuel, by="annee_hydro")
resultat$debit_an<-resultat$debit_an/resultat$N_Qjm*resultat$nb_jours*24*3600/1000


# calcul du flux si demandé
if(out%in%c("flux", "flux_hydrau_pond"))
{
calcul_flux_annuel<-function(i)
{
  calcule_flux(
  analyses,
  debit,
  col_dates_anal = "DatePrel",
  col_analyses = "RsAna",
  methode = methode,
  col_dates_debit = "date_obs_elab",
  col_debits = "resultat_obs_elab",
  date_debut_calcul=seuils_coupure[i],
  date_fin_calcul=(seuils_coupure[i]+lubridate::years(1))-1
)
}

# periodes à calculer : nb résultat analyses suffisant et existence de aleurs de débit
a_calculer<-seq(1,length(lbl_coupure))[resultat$N_RsAna>minimum_rs_ana & !is.na(resultat$N_Qjm) &!is.na(resultat$N_RsAna>minimum_rs_ana)]

 resultat$flux<-NA
 resultat$flux[a_calculer]<-
   lapply(a_calculer, calcul_flux_annuel)%>%
                 unlist()

 # suppression des flux calculés les années où il n'y a pas  assez d'analyses
 try(resultat[resultat$N_RsAna<=minimum_rs_ana,]$flux<-NA, silent=TRUE)
 
 resultat$Cmoy<-resultat$flux/resultat$debit_an*1000
 
}

# calcul de l'hydraulicité si demandé
if(out%in%c("hydrau", "flux_hydrau_pond"))
{
calcul_hydrau_annuel<-function(i)
{
  calcule_hydraulicite(
  debit,
  col_dates_debit = "date_obs_elab",
  col_debits = "resultat_obs_elab",
  date_debut_calcul=seuils_coupure[i],
  date_fin_calcul=(seuils_coupure[i]+lubridate::years(1))-1
)
}
# periodes à calculer : nb résultat analyses suffisant et existence de aleurs de débit
a_calculer<-seq(1,length(lbl_coupure))[!is.na(resultat$N_Qjm)]

resultat$hydraulicity<-NA

 resultat$hydraulicity[a_calculer]<-
   lapply(a_calculer, calcul_hydrau_annuel)%>%
                 unlist()

}

# calcul du flux pondéré par l'hydraulicité
if(out%in%c("flux_hydrau_pond"))
{
resultat$flux_pond<-resultat$flux/resultat$hydraulicity

}
    

return(resultat) 
}


