# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' importe_BV_amont
#' 
#' Function to calculate watershed using GEOSAS API MNT Surf
#' https://geosas.fr/web/?page_id=5877 
#' 
#' @param X : coordonnée du point à partir duquel on souhaite estimer les débits en Lambert 93
#' @param Y :  coordonnée du point à partir duquel on souhaite estimer les débits en Lambert 93
#' 
#' @return sf object with watershed
#' 
#' @export
#' @examples
#' shp<-importe_BV_amont(X=381425.6,
#'                       Y=6755598)
#' 
#' plot(sf::st_geometry(shp))
#' 
importe_BV_amont <- function(X, Y){
   if (!("numeric" %in% class(X))) {
    stop("X doit \u00eatre de type numeric")
  }
  if (!("numeric" %in% class(Y))) {
    stop("Y doit \u00eatre de type numeric")
  }
  

       url_wps <- paste0(
        "https://wps.geosas.fr/mntsurf/?service=wps&request=Execute&identifier=xy2watershed&version=1.0.0&datainputs=X=",
        X,
        ";Y=",
        Y,
        ";formatOut=GeoJSON&rawdataoutput=bvOut"
      )
    
       requete <- httr::GET(url_wps)
      
       if (requete$status_code != 200) {
        stop(paste0("erreur dans code :", requete$status_code))
      }
      
      bv<-sf::st_read(requete$content%>%rawToChar())
      
      return(bv)
      
}
