# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Function wich retrn available dates from SIMFEN API
#' https://geosas.fr/web/?page_id=3804
#' 
#' 
#' @return dataframe with source of flow data and start and end date of data available in the API
#' 
#' @export
#' @examples
#' importe_debit_dates_dispo()
importe_debit_dates_dispo <- function(){
     # récupération des dates de disponibilité des débits depuis le serveur SIMFEN
    url_wps ="https://wps.geosas.fr/simfenV2/?service=WPS&version=1.0.0&request=Execute&identifier=getInfos"
    requete = httr::GET(url_wps)
    httr::content(requete, as = 'parsed')
    tmp<-httr::content(requete, as = 'parsed')%>%
      xml2::as_xml_document()%>%
      xml2::xml_children()%>%
      xml2::as_list()
    
    tmp<-tmp[[3]]$Output$Data$LiteralData[[1]]
    

# Convert the list to a dataframe
df <- data.frame(matrix(unlist(strsplit(tmp,",")), ncol = 3, byrow = T), 
                 stringsAsFactors = F)

# Assign column names to the dataframe
colnames(df) <- c("name", "start_date", "end_date")

# Convert the date columns to Date type
conv_date <- function(x) {
  x <- gsub("Timestamp\\(\\\'", "", x)
  x <- gsub("\\\'\\)", "", x)
  x <- as.Date(x, format = " %Y-%m-%d %H:%M:%S")
}

df$start_date <- conv_date(df$start_date)
df$end_date <- conv_date(df$end_date)
 
df$name<-gsub("\\[", "",df$name)   
df$name<-gsub("\\\'", "",df$name)   
  return(df)
}
