# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' importe_debit_hubeau
#' 
#' This function allows for importing available flow data from the Hydrometry 
#' HUB'EAU API (https://hubeau.eaufrance.fr/page/api-hydrometrie).
#' 
#' @param code_entite character or vector with the code of the hydrometric station 
#' or stations for which we want to retrieve the data (mandatory)
#' @param date_debut_obs_elab start date of observations to retrieve (optional)
#' @param date_fin_obs_elab end date of observations to retrieve (optional)
#'
#' @return the function returns a tibble with the code of the hydrometric station, 
#' the date, and the daily average flow in L/s
#' 
#' @export
#' @examples
#' test<-importe_debit_hubeau(code_entite="J9300611",
#'                      date_debut_obs_elab=as.Date("2010-01-01"),
#'                      date_fin_obs_elab=as.Date("2012-12-31"))
importe_debit_hubeau <-   function(code_entite,
           date_debut_obs_elab = NULL,
           date_fin_obs_elab = NULL) {
    #astuces pour éviter note no visible binding for global variable
  .<- NULL
  
  
    if (!is.character(code_entite)) {
      stop("importe_debit_hubeau : code_entite must be of class character")
    }
    if (!is.null(date_debut_obs_elab)) {
      if (!lubridate::is.Date(date_debut_obs_elab)) {
        stop("importe_debit_hubeau : date_debut_obs_elab must be of class Date")
      }
    } else {
      date_debut_obs_elab <- as.Date("1900-01-01")
    }


    if (!is.null(date_fin_obs_elab)) {
      if (!lubridate::is.Date(date_fin_obs_elab)) {
        stop("importe_debit_hubeau : date_fin_obs_elab must be of class Date")
      }
    } else {
      date_fin_obs_elab <- as.Date(Sys.Date())
    }



    url_base <-
      "https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?"

    data <- httr::GET(
      url_base,
      query = list(
        code_entite = paste0(code_entite, collapse = ","),
        date_debut_obs_elab = date_debut_obs_elab,
        date_fin_obs_elab = date_fin_obs_elab,
        size = 5000,
        grandeur_hydro_elab="QmJ"
        # , fields = "code_station,date_obs_elab,resultat_obs_elab"
      )
    )


    httr::warn_for_status(data)
    httr::stop_for_status(data)

    # si la requête renvoie l'ensemble des données en 1 fois
    if (data$status_code == 200)
    {
      data0 <- data %>%
        httr::content(as = 'text', encoding = "UTF-8") %>%
        jsonlite::fromJSON() %>%
        .$data
    }

    # si la requête nécessite plusieurs pages de résultats alors on parcours les pages de résultat
    if (data$status_code == 206)
    {
      data0 <- data %>%
        httr::content(as = 'text', encoding = "UTF-8") %>%
        jsonlite::fromJSON() %>%
        .$data
      
      url<-"a"

      while (data$status_code == 206 & any(nchar(url)>0))
      {
        # on recupere url page suivante
        url <- data$headers$link %>% stringr::str_split("<")
        url <- lapply(url, function(x)
          stringr::str_split(x, ">"))
        url <- unlist(url)
        url <- url[grep("; rel=\"next\"", url) - 1]

        if(length(url)>0)
       { data <- httr::GET(url)

        data1 <- data %>%
          httr::content(as = 'text', encoding = "UTF-8") %>%
          jsonlite::fromJSON() %>%
          .$data

        if (!is.null(nrow(data1)))
        {
          data0 <- dplyr::bind_rows(data0, data1)
        }}
      }


    }

    if (data$status_code == 400){stop("importe_debit_hubeau : incorrect query")}
    if (data$status_code == 500){stop("importe_stations_hydrometriques_hubeau : hubeau server internal error")}

    return(data0)
}
