# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Imports flow from the SIVA package and calculates mean daily flow
#' 
#' This function will load data from the Arzal dam
#' @inheritParams SIVA::load_debit_barrage
#' @inherit SIVA::load_debit_barrage
#' @return A data frame
#' 
#' @export
#' @examples
#' # Ask anthony or Cédric for the credential file
#' tryCatch({
#'   cred <- yaml::read_yaml("credentials.yml")
#' }, error = function(e) {
#'   stop("You need to have the credentials to connect to SIVA")
#' })
#'
#' hostmysql. <- cred$hostmysql
#' pwdmysql.  <- cred$pwdmysql
#' umysql.    <- cred$usermysql
#'
#' pool <- pool::dbPool(
#'   drv = RMySQL::MySQL(),
#'   dbname = "archive_IAV",
#'   host = hostmysql.,
#'   username = umysql.,
#'   password = pwdmysql.,
#'   port = 3306
#' )
#'
#' importe_debit_siva(debut="2020-01-01 00:00:00",
#'      fin="2020-01-10 00:00:00",
#'      con=pool)
importe_debit_siva <- function(debut,
     fin,
     con){
 
 dat <- SIVA::load_debit_barrage(debut=debut,
     fin=fin,
     con=con)
 param <- SIVA::param
  dj <- SIVA::debit_journalier(dat, type="recalcule")
 return(dj)
}
