# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' This function allows for importing available piezometric data from the Piezometrie 
#' HUB'EAU API (https://hubeau.eaufrance.fr/page/api-piezometrie).
#' 
#' @param code_bss vector with list of old bss code for piezometre (ex. 04193X0022/S2-6) 
#' @param nouveau_bss vector with list of new bss code for piezometre (ex. BSS001DJDP) 
#' @param shp_emprise sf object La fonctionnalité semble non fonctionnelle au 25/05/2023 sous hubeau. A ne pas utiliser avant correction du bug.
#'
#' if both code_bss and nouveau_bss are provided, the function return results only for old bss.
#' if shp_emprise is provided, code_bss and nouveau_bss are not considerated.
#'
#' @return the function returns a tibble with the description of the piezometric station, 
#' 
#' @export
#' @examples
#' # utils::data(sage_vilaine, package="calculeflux")
#' # piezo_vilaine<-importe_stations_piezo_hubeau(shp_emprise=sage_vilaine)
#' data_old_bss<-importe_stations_piezo_hubeau(code_bss=c("04193X0022/S2-6",
#'                                                        "03862X0057/PZ"))
#' data_new_bss<-importe_stations_piezo_hubeau(nouveau_bss=c("BSS001BHVJ",
#'                                                        "BSS001DJDP",
#'     "BSS001ESVY"))
#' 
#'                                  
#' 
importe_stations_piezo_hubeau <- function(code_bss = NULL,
                                          nouveau_bss = NULL,
                                          shp_emprise = NULL) {
  #astuces pour éviter note no visible binding for global variable
  . <- NULL
  
  
  # profondeur de resultat max selon API hubeau
  limite_api_hubeau <- 20000
  
  if (is.null(code_bss) &
      is.null(nouveau_bss) & is.null(shp_emprise)) {
    stop(
      "importe_stations_piezo_hubeau : code_bss, nouveau_bss and shp_emprise can\'t be NULL together"
    )
  }
  if (!is.null(code_bss)) {
    if (!is.character(code_bss) & !is.factor(code_bss)) {
      stop("importe_stations_piezo_hubeau : code_bss must be of class character or factor")
    }
  }
  if (!is.null(nouveau_bss)) {
    if (!is.character(nouveau_bss) & !is.factor(nouveau_bss)) {
      stop(
        "importe_stations_piezo_hubeau : nouveau_bss must be of class character or factor"
      )
    }
  }
  
  if (!is.null(shp_emprise)) {
    if (!"sf" %in% class(shp_emprise)) {
      stop("importe_stations_piezo_hubeau : shp_emprise must be of class sf")
    }
    shp_emprise <- sf::st_transform(shp_emprise, crs = 4326)
  }
  
  #on traite les codes par ordre de priorité
  if (!is.null(shp_emprise)) {
    code_bss <- NULL
    nouveau_bss <- NULL
  }
  
  #on traite les codes par ordre de priorité
  if (!is.null(code_bss)) {
    nouveau_bss <- NULL
  }
  
  # https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?bss_id=BSS001ESVY&format=json&size=20
  
  url_base <-
    "https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?"
  
  ##### On determine le nb de resultat renvoye par la requete #####
  
  ss_fct_requet <- function(code_bss0,
                            nouveau_bss0,
                            shp_emprise0,
                            size0)
  {
    requete <- list(size = size0)
    
    if (!is.null(code_bss0)) {
      requete <-
        c(requete, code_bss = list(paste0(code_bss0, collapse = ",")))
    }
    if (!is.null(nouveau_bss0)) {
      requete <-
        c(requete, bss_id = list(paste0(nouveau_bss0, collapse = ",")))
    }
    
    if (!is.null(shp_emprise0)) {
      requete <-
        c(requete, bbox =list(
          sf::st_bbox(shp_emprise0)[1],
          sf::st_bbox(shp_emprise0)[2],
          sf::st_bbox(shp_emprise0)[3],
          sf::st_bbox(shp_emprise0)[4]
          ))
    }
    
    data <- httr::GET(url_base,
                      query = requete)
    
    httr::warn_for_status(data)
    httr::stop_for_status(data)
    
    return(data)
  }
  
  ss_fct_nb_rslt <- function(data00) {
    nb_result0 <- data00 %>%
      httr::content(as = 'text', encoding = "UTF-8") %>%
      jsonlite::fromJSON()
    
    return(nb_result0$count)
  }
  
  ss_fct_tab_rslt <- function(data00) {
    # print(data00$url)
    if (data00$status_code %in% c(200, 206))
    {
      data00 <- data00 %>%
        httr::content(as = 'text', encoding = "UTF-8") %>%
        jsonlite::fromJSON() %>%
        .$data
    } else
    {
      stop(
        paste0(
          "importe_stations_piezo_hubeau : error in Hubeau API result, status code = ",
          data00$status_code,
          " - url = ",
          data00$url
        )
      )
    }
    return(data00)
  }
  
  
  #nb de resultat renvoyés par la requête
  data0 <- ss_fct_requet(
    code_bss0 = code_bss,
    nouveau_bss0 = nouveau_bss,
    shp_emprise0 = shp_emprise,
    size0 = 10
  )
  
  nb_result <- ss_fct_nb_rslt(data0)
  
  # traitement différencié si tous les résultats peuvent ou pas être exportés par Hubeau.
  # Si oui alors on les exporte, si non, erreur
  if (nb_result <= limite_api_hubeau & nb_result > 0)
  {
    data0 <- ss_fct_requet(
      code_bss0 = code_bss,
      nouveau_bss0 = nouveau_bss,
      shp_emprise0 = shp_emprise,
      size0 = limite_api_hubeau
    )
    
    data0 <- ss_fct_tab_rslt(data0)
    
  } else if (nb_result > 0)
  {
    stop(
      "importe_stations_piezo_hubeau : unable to get all available results, try to restrict input parameters"
    )
  } else {
    data0 <- data.frame()
  }
  
  if (nrow(data0) != nb_result) {
    warning(
      paste0(
        "importe_piezo_hubeau : the fuction return ",
        nrow(data0),
        " lines whereas hubeau API should return ",
        nb_result
      )
    )
  }
  
  return(data0)
  
}
