# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' importe_qualite_hubeau
#' 
#' This function allows for importing available flow data from the Hydrometry 
#' HUB'EAU API (https://hubeau.eaufrance.fr/page/api-hydrometrie).
#' 
#' All codes comes from https://www.sandre.eaufrance.fr/Rechercher-un-jeu-de-donnees.
#' 
#' @param code_station character or vector with the code of the measurement(s) station(s) 
#' @param code_parametre character or vector with the code of required parameter (optional)
#' 
#' @param date_debut start date of observations to retrieve (optional)
#' @param date_fin end date of observations to retrieve (optional)
#'
#' @return the function returns a tibble with the code of the measurement station, 
#' the date, the results, ...
#' 
#' @export
#' @examples
#' donnees<-importe_qualite_hubeau(code_station="04211950", 
#'                                 code_parametre = "1340",
#'                                 code_support="3")
#' 
#' 
importe_qualite_hubeau <-   function(code_station,
                                     code_parametre=NULL,
                                     code_support=NULL,
                                     code_fraction=NULL,
           date_debut = NULL,
           date_fin = NULL) {
    #astuces pour éviter note no visible binding for global variable
  .<- NULL
  
  
    if (!is.character(code_station) & !is.factor(code_station)) {
      stop("importe_qualite_hubeau : code_station must be of class character or factor")
    }
  if (!is.null(code_parametre)) {
      if (!is.character(code_parametre) & !is.factor(code_parametre)) {
        stop("importe_qualite_hubeau : code_parametre must be of class character or factor")
      }
    } 
  if (!is.null(code_support)) {
      if (!is.character(code_support) & !is.factor(code_support)) {
        stop("importe_qualite_hubeau : code_support must be of class character or factor")
      }
    } 
    if (!is.null(code_fraction)) {
      if (!is.character(code_fraction) | !is.factor(code_fraction)) {
        stop("importe_qualite_hubeau : code_fraction must be of class character or factor")
      }
    } 
  
    if (!is.null(date_debut)) {
      if (!lubridate::is.Date(date_debut)) {
        stop("importe_qualite_hubeau : date_debut must be of class Date")
      }
    } else {
      date_debut <- as.Date("1900-01-01")
    }


    if (!is.null(date_fin)) {
      if (!lubridate::is.Date(date_fin)) {
        stop("importe_qualite_hubeau : date_fin must be of class Date")
      }
    } else {
      date_fin <- as.Date(Sys.Date())
    }

    url_base <-
      "https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?"

    requete<-list(
      code_station=list(paste0(code_station, collapse = ",")),
        date_debut_prelevement = date_debut,
        date_fin_prelevement = date_fin,
        size = 10000
      )
    

    if(!is.null(code_parametre)){requete<-c(requete, code_parametre=list(paste0(code_parametre, collapse = ",")))}
    if(!is.null(code_support)){requete<-c(requete, code_support=list(paste0(code_support, collapse = ",")))}
    if(!is.null(code_fraction)){requete<-c(requete, code_fraction=list(paste0(code_fraction, collapse = ",")))}
    
    data <- httr::GET(
      url_base,
      query = requete
    )


    httr::warn_for_status(data)
    httr::stop_for_status(data)

    # si la requête renvoie l'ensemble des données en 1 fois
    if (data$status_code == 200)
    {
      data0 <- data %>%
        httr::content(as = 'text', encoding = "UTF-8") %>%
        jsonlite::fromJSON() %>%
        .$data
    }

    # si la requête nécessite plusieurs pages de résultats alors on parcours les pages de résultat
    if (data$status_code == 206)
    {
      data0 <- data %>%
        httr::content(as = 'text', encoding = "UTF-8") %>%
        jsonlite::fromJSON() %>%
        .$data
      
      url<-"a"

      while (data$status_code == 206 & nchar("url">0))
      {
        # on recupere url page suivante
        url <- data$headers$link %>% stringr::str_split("<")
        url <- lapply(url, function(x)
          stringr::str_split(x, ">"))
        url <- unlist(url)
        url <- url[grep("; rel=\"next\"", url) - 1]

        data <- httr::GET(url)

        data1 <- data %>%
          httr::content(as = 'text', encoding = "UTF-8") %>%
          jsonlite::fromJSON() %>%
          .$data

        if (!is.null(nrow(data1)))
        {
          data0 <- dplyr::bind_rows(data0, data1)
        }
      }


    }

    if (data$status_code == 400){stop("importe_qualite_hubeau : incorrect query")}
    if (data$status_code == 500){stop("importe_qualite_hubeau : hubeau server internal error")}

    return(data0)
}
