# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' importe_stations_hydrometriques_hubeau
#' This function allows for importing available hydrometric stations from the 
#' Hydrometry HUB'EAU API (https://hubeau.eaufrance.fr/page/api-hydrometrie).
#' 
#' @param emprise object of class sf which define the area of the request
#'
#' @return the function returns a sf object with informations about the hydrometric 
#' station
#' 
#' @export
#' @examples
#' utils::data(sage_vilaine, package="calculeflux")
#'   test<-importe_stations_hydrometriques_hubeau(emprise=sage_vilaine)
#'
#'   plot(sage_vilaine)
#'   plot(test, add=TRUE)
importe_stations_hydrometriques_hubeau <-   function(emprise) {
  #astuce pour éviter note no visible binding for global variable
  .<- NULL
 
    if (!"sf"%in%class(emprise)) {
      stop("importe_stations_hydrometriques_hubeau : emprise must be an object of class sf")
    }

  
tryCatch(emprise0<-sf::st_transform(emprise, crs=4326),
  error = function(e) {
    # code to handle the error
    message(
      "importe_stations_hydrometriques_hubeau : Error in converting the projection 
      of 'emprise'. Verify that the input file's st_crs is properly filled in."
    )
  })

  bbox<-sf::st_bbox(emprise0)
  
    url_base <-
      "https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?"

    data <- httr::GET(url_base,
                      query = list(bbox = paste0(bbox, collapse = ","),
                                   size = 500))
    
    
    httr::warn_for_status(data)
    httr::stop_for_status(data)
    
    # si la requête renvoie l'ensemble des données en 1 fois
    if (data$status_code == 200)
    {
      data0 <- data %>%
        httr::content(as = 'text', encoding = "UTF-8") %>%
        jsonlite::fromJSON() %>%
        .$data
    }
    
    # si la requête nécessite plusieurs pages de résultats alors on parcours les pages de résultat
    if (data$status_code == 206)
    {
      data0 <- data %>%
        httr::content(as = 'text', encoding = "UTF-8") %>%
        jsonlite::fromJSON() %>%
        .$data
      
      url <- "a"
      
      while (data$status_code == 206 & any(nchar(url) > 0))
      {
        # on recupere url page suivante
        url <- data$headers$link %>% stringr::str_split("<")
        url <- lapply(url, function(x)
          stringr::str_split(x, ">"))
        url <- unlist(url)
        url <- url[grep("; rel=\"next\"", url) - 1]
        
        if (length(url) > 0) {
          data <- httr::GET(url)
          
          data1 <- data %>%
            httr::content(as = 'text', encoding = "UTF-8") %>%
            jsonlite::fromJSON() %>%
            .$data
          
          if (!is.null(nrow(data1)))
          {
            data0 <- dplyr::bind_rows(data0, data1)
          }
        }
      }
    }

    if (data$status_code == 400){stop("importe_stations_hydrometriques_hubeau : incorrect query")}
    if (data$status_code == 500){stop("importe_stations_hydrometriques_hubeau : hubeau server internal error")}
    
    data0<-sf::st_as_sf(data0, 
                        coords=c("longitude_station", "latitude_station"),
                        crs=4326)

    data0<-sf::st_transform(data0, sf::st_crs(emprise))
    data0<-data0[emprise,]
    
    return(data0)
}
